name: forex_mountain
description: "A new Flutter project."
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^1.1.6
  mj_image_slider: ^0.0.7
  cached_network_image: ^3.4.1
  flick_video_player: ^0.8.0
  video_player: ^2.9.1
  vimeo_video_player: ^0.0.16
  http: ^1.2.2
  qr_flutter: ^4.1.0
  awesome_dialog: ^3.2.1
  dropdown_search: ^5.0.6
  flutter_animation_progress_bar: ^2.3.1
  url_launcher: ^6.3.0
  intl: ^0.19.0
  flutter_timezone: ^3.0.0
  page_transition: ^2.1.0
  flutter_color_utils: ^0.0.1
  chat_bubbles: ^1.6.0
  animated_tree_view: ^2.2.1
  custom_clippers: ^2.0.0
  google_fonts: ^6.2.1
  visibility_detector: ^0.4.0+2
  pin_input_text_field: ^4.5.2
  pull_to_refresh: ^2.0.0
  carousel_slider: ^5.0.0
  coupon_uikit: ^0.2.1
  smooth_page_indicator: ^1.2.0+3
  sticky_headers: ^0.3.0+2
  syncfusion_flutter_charts: ^27.1.51
  graphview: ^1.2.0
  flutter_html_all: ^3.0.0-beta.2
  provider: ^6.1.2
  get: ^4.6.6
  api_cache_manager: ^1.0.2
  get_it: ^7.7.0
  sqflite: ^2.3.3+1
  shared_preferences: ^2.3.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.2.2
  path_provider: ^2.1.4
  intl_phone_field: ^3.2.0
  connectivity_plus: ^6.0.5
  fluttertoast: ^8.2.8
  rive: ^0.13.4
  cherry_toast: ^1.11.0
  lottie: ^3.1.2
  circular_progress_bar_with_lines: ^0.0.7
  action_slider: ^0.7.0
  flutter_cache_manager: ^3.4.1
  package_info_plus: ^8.0.2
  local_auth: ^2.3.0
  device_info_plus: ^10.1.2
  flutter_rating_bar: ^4.0.1
  envied: ^0.5.4+1
  flutter_branch_sdk: ^7.1.0
  share_plus: ^10.0.2
  uni_links: ^0.5.1
  ansicolor: ^2.0.3
  timelines: ^0.1.0
  in_app_review: ^2.0.9
  in_app_update: ^4.2.3
  simple_gradient_text: ^1.3.0
  youtube_explode_dart: ^2.2.1
  pod_player: ^0.2.2
  audio_video_progress_bar: ^2.0.3
  slide_countdown: ^1.6.1
  flutter_flip_card: ^0.0.6
  flutter_spinkit: ^5.2.1
  flutter_custom_clippers: ^2.1.0
  dio: ^5.6.0
  flutter_rounded_date_picker: ^3.0.4
  toggle_switch: ^2.3.0
  flutter_breadcrumb: ^1.0.1
  loadmore: ^2.1.0
  swipeable_tile: ^2.0.1
  banner_carousel: ^1.2.1
  flutter_fancy_tree_view: ^1.6.0
  path_drawing: ^1.0.1
  version: ^3.0.2
  os_detect: ^2.0.1
  pdf: ^3.11.1
  printing: ^5.13.2
  open_file: ^3.4.0
  floating_chat_button: ^1.1.0
  percent_indicator: ^4.2.3
  activity_ring: ^0.3.0
  youtube_player_flutter: ^9.0.3
  html: ^0.15.4
  auto_size_text: ^3.0.0
  firebase_crashlytics: ^3.4.9
  logger: ^2.4.0
  in_app_purchase: ^3.2.0
  permission_handler: ^11.3.1
  pedometer: ^4.0.2
  vimeo_player_flutter: ^0.1.0
  flutter_app_badger: ^1.5.0

  in_app_purchase_android: any
  in_app_purchase_storekit: any
  timezone: any
  xml: any
  nested: any
  webview_flutter: any
  webview_flutter_android: any
  webview_flutter_wkwebview: any
  flutter_html: any
  collection: any
  android_id: ^0.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.3.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appLogo_s.png"
  min_sdk_android: 21
  remove_alpha_ios: true
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/images/card_images/
    - assets/videos/
    - assets/rive/
    - assets/lottie/
    - icons/

  fonts:
    - family: halter
      fonts:
        - asset: font/halter.ttf

