// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQdnxXxfJPlm5BsoQnkFwEWuCoBMMebVY',
    appId: '1:519172440309:web:3af0111c102fad86f585bc',
    messagingSenderId: '519172440309',
    projectId: 'eagle-mountain',
    authDomain: 'eagle-mountain.firebaseapp.com',
    storageBucket: 'eagle-mountain.firebasestorage.app',
    measurementId: 'G-7KLKE7YYLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzHps8s51hjbUaOf2st3AyLNbd_OUVMyU',
    appId: '1:519172440309:android:d3656da2f81d8e50f585bc',
    messagingSenderId: '519172440309',
    projectId: 'eagle-mountain',
    storageBucket: 'eagle-mountain.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzKNMyxR_tZqmdZkcLr7f2K-rdTcGsozc',
    appId: '1:519172440309:ios:8ff915795ba9d0d4f585bc',
    messagingSenderId: '519172440309',
    projectId: 'eagle-mountain',
    storageBucket: 'eagle-mountain.firebasestorage.app',
    iosBundleId: 'com.example.foresMountain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzKNMyxR_tZqmdZkcLr7f2K-rdTcGsozc',
    appId: '1:519172440309:ios:8ff915795ba9d0d4f585bc',
    messagingSenderId: '519172440309',
    projectId: 'eagle-mountain',
    storageBucket: 'eagle-mountain.firebasestorage.app',
    iosBundleId: 'com.example.foresMountain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQdnxXxfJPlm5BsoQnkFwEWuCoBMMebVY',
    appId: '1:519172440309:web:5dea42cabcfceb37f585bc',
    messagingSenderId: '519172440309',
    projectId: 'eagle-mountain',
    authDomain: 'eagle-mountain.firebaseapp.com',
    storageBucket: 'eagle-mountain.firebasestorage.app',
    measurementId: 'G-N54VPRL057',
  );
}
